## DAY-10

In [1]:
import numpy as np

In [2]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [3]:
updated=[]
for i in h:
    updated.append(7+i)
print("Original list:",h)
print("Updated list after adding 7:",updated)

Original list: [30, 20, 5, 8, 9]
Updated list after adding 7: [37, 27, 12, 15, 16]


In [4]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [5]:
d=[]
for i in s:
    d.append(i*i)
print("Squares of numbers in tuple:",d)

Squares of numbers in tuple: [36, 4, 9, 81, 49, 25, 64]


In [6]:
e=tuple(d)
e
print("Squares of numbers in tuple:",e)

Squares of numbers in tuple: (36, 4, 9, 81, 49, 25, 64)


In [7]:
type(e)

tuple

In [8]:
s

(6, 2, 3, 9, 7, 5, 8)

In [9]:
arr=np.array([20,45,2,1,8,5,51,484,8,48,484,8,89])
arr

array([ 20,  45,   2,   1,   8,   5,  51, 484,   8,  48, 484,   8,  89])

In [10]:
arr+7  #using this pandas we can easily access the elements with out using any for loop

array([ 27,  52,   9,   8,  15,  12,  58, 491,  15,  55, 491,  15,  96])

In [11]:
arr  #The operations are always temporary they are not stored

array([ 20,  45,   2,   1,   8,   5,  51, 484,   8,  48, 484,   8,  89])

In [12]:
x=arr+7  #u can assign the values to the variables for storing and using further
x

array([ 27,  52,   9,   8,  15,  12,  58, 491,  15,  55, 491,  15,  96])

In [13]:
arr*5

array([ 100,  225,   10,    5,   40,   25,  255, 2420,   40,  240, 2420,
         40,  445])

In [14]:
arr>50

array([False, False, False, False, False, False,  True,  True, False,
       False,  True, False,  True])

In [15]:
k=arr
k

array([ 20,  45,   2,   1,   8,   5,  51, 484,   8,  48, 484,   8,  89])

In [16]:
arr[arr>50]    #directly prints the elements which are greater than 50

array([ 51, 484, 484,  89])

In [17]:
[k>50]  #directly prints the elements which are greater than 50

[array([False, False, False, False, False, False,  True,  True, False,
        False,  True, False,  True])]

In [18]:
k[k>50]  #directly prints the elements 

array([ 51, 484, 484,  89])

In [19]:
k[k>40]

array([ 45,  51, 484,  48, 484,  89])

In [20]:
k

array([ 20,  45,   2,   1,   8,   5,  51, 484,   8,  48, 484,   8,  89])

In [21]:
index=[]
for i in range(len(k)):
    if k[i]>50:
        index.append(i)
index  #prints the position of the elements where the elements are located>50

[6, 7, 10, 12]

In [22]:
arr[arr>50]  #Directly prints elements present which are greater than 50

array([ 51, 484, 484,  89])

In [24]:
np.where(arr>50)  #Prints the indexes of the elements which are greater than50

(array([ 6,  7, 10, 12], dtype=int64),)