## DAY-12

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
k=(45,85,96,78,21,644,78,0,10,20)

In [4]:
pd.Series(k)  #This converts the list to a series object

0     45
1     85
2     96
3     78
4     21
5    644
6     78
7      0
8     10
9     20
dtype: int64

In [5]:
pd.DataFrame(k) #function same 

0
0   45
1   85
2   96
3   78
4   21
5  644
6   78
7    0
8   10
9   20

In [6]:
a=np.random.randint(20,50,(4,5))
a

array([[49, 31, 45, 48, 23],
       [33, 40, 35, 27, 34],
       [24, 36, 49, 29, 32],
       [41, 37, 39, 36, 22]])

In [7]:
a

array([[49, 31, 45, 48, 23],
       [33, 40, 35, 27, 34],
       [24, 36, 49, 29, 32],
       [41, 37, 39, 36, 22]])

In [8]:
a.ndim

2

In [9]:
pd.DataFrame(a)

0   1   2   3   4
0  49  31  45  48  23
1  33  40  35  27  34
2  24  36  49  29  32
3  41  37  39  36  22

In [10]:
df1=pd.DataFrame(a,columns=['Roll_no','Id','Age','Marks','Height'],## It is used to assign the column names for the data 
                index=['CS483','CS486','CS517','CS466'])## It is used to assign the ROW  names for the data 
df1  

Roll_no  Id  Age  Marks  Height
CS483       49  31   45     48      23
CS486       33  40   35     27      34
CS517       24  36   49     29      32
CS466       41  37   39     36      22

In [11]:
sns.get_dataset_names()  #It is a function used to load the datsets available in the seaborn module

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [12]:
df=sns.load_dataset('flights')
df

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [13]:
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [14]:
df=sns.load_dataset('taxis')
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [15]:
type(df) 

pandas.core.frame.DataFrame

In [16]:
df.shape  #Tuple gives column number and row numbers

(6433, 14)

In [17]:
df.shape[1] #prints the number of rows available

14

In [18]:
df.columns #Displays the names of the columns present in the datset named  taxis

Index(['pickup', 'dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls',
       'total', 'color', 'payment', 'pickup_zone', 'dropoff_zone',
       'pickup_borough', 'dropoff_borough'],
      dtype='object')

In [19]:
df['color'].unique()

array(['yellow', 'green'], dtype=object)

In [20]:
c=df.info()
c

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64         
 3   distance         6433 non-null   float64       
 4   fare             6433 non-null   float64       
 5   tip              6433 non-null   float64       
 6   tolls            6433 non-null   float64       
 7   total            6433 non-null   float64       
 8   color            6433 non-null   object        
 9   payment          6389 non-null   object        
 10  pickup_zone      6407 non-null   object        
 11  dropoff_zone     6388 non-null   object        
 12  pickup_borough   6407 non-null   object        
 13  dropoff_borough  6388 non-null   object        
dtypes: datetime64[ns](2), float64(5), int64(

In [21]:
df['color'].unique()

array(['yellow', 'green'], dtype=object)

In [22]:
df['color'].value_counts  ## Shows the all color details

<bound method IndexOpsMixin.value_counts of 0       yellow
1       yellow
2       yellow
3       yellow
4       yellow
         ...  
6428     green
6429     green
6430     green
6431     green
6432     green
Name: color, Length: 6433, dtype: object>

In [23]:
df['color'].value_counts() #Shows the exact count of colors

color
yellow    5451
green      982
Name: count, dtype: int64

In [24]:
df['payment'] #Shows the total number of payment options

0       credit card
1              cash
2       credit card
3       credit card
4       credit card
           ...     
6428    credit card
6429    credit card
6430           cash
6431    credit card
6432    credit card
Name: payment, Length: 6433, dtype: object

In [25]:
df['payment'].unique()  #Shows the kind of operations unique() is used to show the missing datya in value and print the all possible outcomes of a data

array(['credit card', 'cash', nan], dtype=object)

In [26]:
df['payment'].value_counts()

payment
credit card    4577
cash           1812
Name: count, dtype: int64

In [27]:
df['fare']

0        7.0
1        5.0
2        7.5
3       27.0
4        9.0
        ... 
6428     4.5
6429    58.0
6430    16.0
6431     6.0
6432    15.0
Name: fare, Length: 6433, dtype: float64

In [28]:
df['fare'].unique()

array([  7.  ,   5.  ,   7.5 ,  27.  ,   9.  ,  13.  ,   8.5 ,  15.  ,
         8.  ,  17.  ,   6.5 ,  10.5 ,  11.5 ,  13.5 ,   9.5 ,   5.5 ,
        31.5 ,  10.  ,  12.5 ,  17.5 ,  12.  ,   4.  ,   4.5 ,  20.5 ,
        20.  ,  80.  ,  28.  ,  29.5 ,  36.  ,  19.  ,  52.  ,  18.5 ,
        15.5 ,   6.  ,  16.5 ,  30.  ,  16.  ,   2.5 ,   3.  ,  33.5 ,
        11.  ,  39.5 ,  37.61,  14.5 ,  14.  ,  23.  ,  34.  ,  28.5 ,
         3.5 ,  24.  ,  40.  ,  23.5 ,  46.5 ,  27.5 ,  48.5 ,  19.5 ,
        32.  ,  38.5 ,  40.5 ,  26.  ,  50.5 ,  18.  ,  22.  ,  35.5 ,
        45.  ,  25.5 ,  36.5 ,  30.5 ,  21.  ,  33.  ,  21.5 ,  37.58,
        22.5 ,  24.5 ,  37.  ,  47.5 ,  31.  ,  41.53, 120.  ,  32.5 ,
        44.  ,  49.  ,  57.  ,  38.  ,  39.  ,  29.  ,  42.  ,  23.32,
        49.5 ,  67.5 ,  35.  ,   1.  ,  43.5 ,  44.5 ,  59.5 ,  26.5 ,
        72.  ,  56.  ,  41.  ,  37.5 ,  42.5 ,  50.  ,  43.  ,  46.01,
        36.02,  25.  ,  27.06, 130.  ,  69.06,  84.  ,  27.22,  51.5 ,
      

In [29]:
df['fare'].value_counts()

fare
7.50     350
6.00     345
6.50     323
5.00     313
5.50     312
        ... 
96.50      1
75.50      1
31.67      1
45.71      1
26.32      1
Name: count, Length: 220, dtype: int64

In [30]:
df['fare'].median()

9.5

In [31]:
df['fare'].mean()

13.091072594434944

In [32]:
df['fare'].mode()

0    7.5
Name: fare, dtype: float64

In [33]:
df['fare'].var()

133.4441818095617

In [34]:
df['fare'].std()

11.55180426641491