##  DAY-09

In [1]:
import numpy as np

In [2]:
j=[4,6,2,8,9]
type(j)

list

In [3]:
np.array(j)  #converts the list into an array

array([4, 6, 2, 8, 9])

In [4]:
tuple(j)  #Directly converts to a tuple

(4, 6, 2, 8, 9)

In [5]:
n=[4,8,4,5,7,5,4]
d=np.array(n)

In [6]:
type(d) #SHows the type of a array

numpy.ndarray

In [7]:
d

array([4, 8, 4, 5, 7, 5, 4])

In [8]:
d.shape

(7,)

In [9]:
n

[4, 8, 4, 5, 7, 5, 4]

In [10]:
n.shape  #List does not have any shape attribute

AttributeError: 'list' object has no attribute 'shape'

In [11]:
d.shape #Indicates the  number of elements int the list

(7,)

In [12]:
d.ndim  #Indicates the dimension of list

1

In [13]:
d.size  #Indicates the size of list

7

In [14]:
s=[[4, 8, 4, 5, 7, 5, 4],[74, 88, 74, 45, 7, 15, 64],[48, 88, 48, 57, 27, 15, 44],[94, 68, 44, 65, 27, 25, 34]]
s

[[4, 8, 4, 5, 7, 5, 4],
 [74, 88, 74, 45, 7, 15, 64],
 [48, 88, 48, 57, 27, 15, 44],
 [94, 68, 44, 65, 27, 25, 34]]

In [15]:
type(s)

list

In [16]:
arr1=np.array(s)
arr1

array([[ 4,  8,  4,  5,  7,  5,  4],
       [74, 88, 74, 45,  7, 15, 64],
       [48, 88, 48, 57, 27, 15, 44],
       [94, 68, 44, 65, 27, 25, 34]])

In [17]:
arr1.shape      # 4-rows and 7-columns

(4, 7)

In [18]:
arr1.size

28

In [19]:
arr1.ndim

2

In [20]:
arr1.reshape

<function ndarray.reshape>

In [21]:
arr1.reshape(7,4)

array([[ 4,  8,  4,  5],
       [ 7,  5,  4, 74],
       [88, 74, 45,  7],
       [15, 64, 48, 88],
       [48, 57, 27, 15],
       [44, 94, 68, 44],
       [65, 27, 25, 34]])

In [22]:
arr1.shape

(4, 7)

In [23]:
arr1.size

28

In [24]:
arr1.ndim

2

In [25]:
d

array([4, 8, 4, 5, 7, 5, 4])

In [26]:
d.ndim

1

In [27]:
d.shape

(7,)

In [28]:
d.size

7

In [29]:
arr1

array([[ 4,  8,  4,  5,  7,  5,  4],
       [74, 88, 74, 45,  7, 15, 64],
       [48, 88, 48, 57, 27, 15, 44],
       [94, 68, 44, 65, 27, 25, 34]])

In [30]:
arr1.ndim

2

In [31]:
arr1.reshape(7,4)

array([[ 4,  8,  4,  5],
       [ 7,  5,  4, 74],
       [88, 74, 45,  7],
       [15, 64, 48, 88],
       [48, 57, 27, 15],
       [44, 94, 68, 44],
       [65, 27, 25, 34]])

In [32]:
arr1.reshape(7,4)

array([[ 4,  8,  4,  5],
       [ 7,  5,  4, 74],
       [88, 74, 45,  7],
       [15, 64, 48, 88],
       [48, 57, 27, 15],
       [44, 94, 68, 44],
       [65, 27, 25, 34]])

In [33]:
arr=[[4,5,6,7,8],[1,2,3,4,5],[7,8,9,4,15],[7,8,9,4,5],[1,2,3,4,5]]

In [34]:
k=np.array(arr)
k

array([[ 4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5],
       [ 7,  8,  9,  4, 15],
       [ 7,  8,  9,  4,  5],
       [ 1,  2,  3,  4,  5]])

In [35]:
k.shape

(5, 5)

In [36]:
k.size

25

In [37]:
k.reshape(5,1,5)

array([[[ 4,  5,  6,  7,  8]],

       [[ 1,  2,  3,  4,  5]],

       [[ 7,  8,  9,  4, 15]],

       [[ 7,  8,  9,  4,  5]],

       [[ 1,  2,  3,  4,  5]]])

In [38]:
k.ndim

2

In [39]:
k.size

25

In [40]:
arr1

array([[ 4,  8,  4,  5,  7,  5,  4],
       [74, 88, 74, 45,  7, 15, 64],
       [48, 88, 48, 57, 27, 15, 44],
       [94, 68, 44, 65, 27, 25, 34]])

In [41]:
arr1.reshape(7,2,2,1,1)

array([[[[[ 4]],

         [[ 8]]],


        [[[ 4]],

         [[ 5]]]],



       [[[[ 7]],

         [[ 5]]],


        [[[ 4]],

         [[74]]]],



       [[[[88]],

         [[74]]],


        [[[45]],

         [[ 7]]]],



       [[[[15]],

         [[64]]],


        [[[48]],

         [[88]]]],



       [[[[48]],

         [[57]]],


        [[[27]],

         [[15]]]],



       [[[[44]],

         [[94]]],


        [[[68]],

         [[44]]]],



       [[[[65]],

         [[27]]],


        [[[25]],

         [[34]]]]])

In [42]:
range(5,20)

range(5, 20)

In [43]:
m=[3,4,5,6,7,10,11,14,15]
m

[3, 4, 5, 6, 7, 10, 11, 14, 15]

In [44]:
list(range(3,13))   #Displays the size and elements in that particular list      

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [45]:
list(range(3,19,2)) #(start,end,step_size)

[3, 5, 7, 9, 11, 13, 15, 17]

In [46]:
list(range(0,1300,100))

[0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200]

In [47]:
m=range(-10,1,1)

In [48]:
list(m)

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [49]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [50]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [51]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [52]:
#Draw back of the range function is it could not work for float values

In [53]:
list(range(-1.5,10,-1))

TypeError: 'float' object cannot be interpreted as an integer

In [54]:
[8.5,6,2.3,5.6,1.0,2.0,8]


[8.5, 6, 2.3, 5.6, 1.0, 2.0, 8]

In [55]:
range(5,50,5)

range(5, 50, 5)

In [56]:
for i in range(5,50,5):
    print("Data",i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [57]:
j=[5,87,52,3,21,41,65,54,1,8]
j

[5, 87, 52, 3, 21, 41, 65, 54, 1, 8]

In [58]:
#This is the program to separate elements based on position if pos is odd go in odd list if even go to the even list

even_pos=[]
odd_pos=[]
for i in range(len(j)):
    if i%2==0:
        even_pos.append(j[i])
    else:
        odd_pos.append(j[i])
        

print("Even position Numbers:",even_pos)
print("Odd position Numbers:",odd_pos)

Even position Numbers: [5, 52, 21, 65, 1]
Odd position Numbers: [87, 3, 41, 54, 8]


# DISTRIBUTION

In [59]:
import numpy as np

In [60]:
j

[5, 87, 52, 3, 21, 41, 65, 54, 1, 8]

In [61]:
k=np.array(j)
k

array([ 5, 87, 52,  3, 21, 41, 65, 54,  1,  8])

In [62]:
k.mean()  # use to find the mean

33.7

In [63]:
np.mean(k) #another method to find mean

33.7

In [64]:
np.median(k) #use to find median

31.0

In [65]:
np.var(k)  #Shows the variance

827.8100000000001

In [66]:
np.min(k)  #Finds the minimum number in the list

1

In [67]:
np.max(k) #Finds the maximum element

87

In [68]:
np.quantile(k,0.25) 

5.75

In [69]:
np.random.rand() #Function used to generate a random value in the limit of 0 to 1

0.5419898203023007

In [70]:
r=np.random.rand(100)
r

array([0.3244516 , 0.69346549, 0.98234029, 0.3148783 , 0.63108228,
       0.79687159, 0.75148088, 0.48244922, 0.14674786, 0.81550381,
       0.95446304, 0.82048828, 0.50752672, 0.6133436 , 0.23392466,
       0.03131482, 0.25366377, 0.00699871, 0.21959834, 0.94144096,
       0.70943809, 0.07052109, 0.20009631, 0.89073641, 0.3842485 ,
       0.99195478, 0.05678245, 0.09827806, 0.18280144, 0.43252442,
       0.91075694, 0.15613691, 0.74058662, 0.78491395, 0.38926704,
       0.43335946, 0.68986899, 0.46847951, 0.91920461, 0.61789027,
       0.15830768, 0.25680956, 0.32075871, 0.02243225, 0.06182657,
       0.97106822, 0.96405233, 0.28484984, 0.67403358, 0.0211559 ,
       0.67028688, 0.46324242, 0.52020758, 0.64331515, 0.30757258,
       0.54252767, 0.1459075 , 0.90224302, 0.28964917, 0.31860694,
       0.49041863, 0.70341908, 0.21008164, 0.51590086, 0.94038402,
       0.69916174, 0.16979271, 0.1977748 , 0.77393106, 0.00298135,
       0.91257162, 0.44440815, 0.58476691, 0.85157389, 0.80070

In [71]:
r.shape

(100,)

In [72]:
r.size

100

In [73]:
r.ndim

1

In [74]:
m=np.random.rand(5,3) #creates the array in the 2dimension

In [75]:
m

array([[0.24219941, 0.30074798, 0.99639072],
       [0.55636069, 0.12882245, 0.86286533],
       [0.51799751, 0.40993085, 0.17595225],
       [0.79188992, 0.85862069, 0.90913074],
       [0.20362353, 0.36717311, 0.55545822]])

In [76]:
m.size

15

In [77]:
m.ndim

2

In [78]:
m.shape

(5, 3)

## STANDARD NORMAL DISTRUBUTION

In [79]:
np.random.randn() #This is the function it is used to create standard normal distrubution random values

-2.3246436794160394

In [80]:
n=np.random.randn(10,4)
n

array([[-0.72088059,  0.17836982, -0.77672782, -0.24941229],
       [-0.10737888, -0.71041788,  0.15754652, -0.72595483],
       [ 0.28549947, -1.23669016, -0.60851174,  0.47059842],
       [-1.26954887, -1.03107089, -1.32067165,  0.89479347],
       [ 0.92408728,  1.41700109, -0.07795448, -1.75673174],
       [-0.30972952, -0.68069816, -0.62776199, -0.19884798],
       [ 0.0902426 , -0.41352328, -0.40152465,  0.6063215 ],
       [ 0.24698498,  0.66686073, -1.15691552,  0.2550248 ],
       [-0.44812145,  2.46564388, -0.71091451,  1.12013726],
       [ 0.15579674,  0.24009426,  0.33303606, -0.61562381]])

In [81]:
np.random.randn(30,1) #RANDOM normal distribution will have range of -3 to +3 and has standard normal data
                    #Range will be 0-1

array([[ 1.09475123],
       [ 0.31431695],
       [ 0.68153864],
       [-0.96233702],
       [ 0.1977553 ],
       [-1.86089987],
       [ 0.38825301],
       [ 0.31253697],
       [ 0.98415852],
       [ 0.10393682],
       [-2.27571756],
       [ 0.81002926],
       [ 1.16776654],
       [-0.3564891 ],
       [-0.38964326],
       [ 1.05501481],
       [-0.20525284],
       [-0.3764801 ],
       [ 1.22258801],
       [-0.26237537],
       [ 0.15192322],
       [-1.08176709],
       [-0.42114054],
       [ 0.48294265],
       [ 0.0080162 ],
       [ 1.27434501],
       [ 0.11935651],
       [-2.4122367 ],
       [-0.20738484],
       [-1.60486576]])

#### In this mean=0 and standard deviation is=0

## NORMAL DISTRUBUTION

#### In this we need mean and variance

In [82]:
np.random.normal()                # Generates the value randomly but in normal

-0.4065540578995381

In [83]:
np.random.normal(40,5)  

43.23132855843623

#### The skeleton for traversing:  (mean,variance,(start,begin,step_size))

In [84]:
np.random.normal(40,5,(7,4))       #(40,5)--> this is the mean and variance

array([[39.94133276, 45.52273322, 41.51908113, 40.9841711 ],
       [33.8889039 , 36.64842007, 40.66412426, 39.07959504],
       [53.41401502, 32.20336056, 43.38118505, 33.95531542],
       [39.51465207, 42.71212995, 33.73413223, 48.59398728],
       [42.14994078, 37.99128824, 45.26861152, 35.67546777],
       [39.96394114, 43.32571137, 34.6925518 , 42.57867867],
       [33.70293738, 46.83566335, 40.81656781, 33.43449189]])

In [89]:
np.random.normal(40,5,(7,4,5))  

array([[[40.13403901, 38.34477591, 39.40143341, 44.31158273,
         40.61085215],
        [40.79121116, 42.49971593, 36.87339829, 41.27210845,
         36.84698144],
        [42.09261218, 35.66454615, 40.24026704, 37.95832004,
         42.83986832],
        [41.88986084, 43.64157956, 36.02953192, 32.69254486,
         38.98426246]],

       [[36.57040302, 43.68826779, 49.12871882, 45.26935453,
         44.26867886],
        [41.53680277, 38.64121462, 42.71823419, 42.89044312,
         31.2348516 ],
        [38.77116703, 40.51555042, 22.88080703, 40.75260178,
         38.70487644],
        [38.38563021, 42.11370125, 42.7081086 , 40.9379885 ,
         40.7238589 ]],

       [[31.54338797, 41.09959487, 40.60063473, 41.02974906,
         35.05292942],
        [46.35105998, 40.11346556, 38.68434759, 43.81355717,
         45.68280786],
        [42.23199503, 47.05804748, 36.04052755, 43.21641014,
         45.84705098],
        [45.16011464, 38.24994427, 32.7966056 , 44.49747187,
         39

In [90]:
np.random.randint(35,100)   # uising this we can generate the random integer in between the given the specific values range

96

In [91]:
np.random.randint(35,100,20)

array([73, 85, 67, 89, 49, 97, 52, 65, 66, 57, 58, 62, 61, 74, 40, 68, 47,
       79, 96, 82])

In [92]:
np.random.randint(35,100,200)

array([94, 62, 60, 46, 65, 53, 96, 51, 40, 73, 68, 40, 62, 89, 60, 51, 62,
       88, 94, 38, 56, 57, 95, 72, 45, 62, 73, 69, 69, 55, 78, 77, 39, 35,
       95, 46, 56, 35, 38, 42, 55, 86, 95, 42, 90, 66, 44, 47, 98, 60, 60,
       48, 39, 39, 39, 65, 91, 93, 51, 98, 58, 84, 49, 50, 56, 60, 79, 78,
       41, 88, 76, 48, 42, 78, 55, 84, 41, 48, 64, 83, 75, 77, 45, 97, 70,
       40, 61, 69, 62, 85, 93, 99, 84, 95, 41, 91, 84, 90, 47, 87, 52, 47,
       35, 61, 74, 41, 37, 75, 41, 60, 77, 85, 62, 84, 67, 87, 45, 96, 96,
       89, 94, 40, 81, 65, 91, 74, 42, 51, 95, 91, 75, 37, 99, 39, 62, 87,
       67, 66, 36, 82, 92, 93, 99, 62, 58, 71, 53, 99, 96, 91, 61, 77, 85,
       75, 69, 86, 47, 44, 53, 64, 57, 45, 39, 67, 81, 69, 77, 49, 55, 74,
       59, 70, 65, 95, 97, 76, 63, 80, 93, 76, 63, 76, 51, 56, 59, 51, 38,
       91, 64, 57, 76, 67, 80, 86, 85, 65, 74, 98, 60, 98])

In [93]:
np.random.randint(35,100,(5,5))

array([[73, 44, 51, 38, 54],
       [61, 44, 57, 78, 77],
       [81, 97, 54, 36, 41],
       [75, 98, 44, 48, 90],
       [73, 55, 59, 65, 60]])